spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/dev
  profiles:
     active: native

server:
  port: 8888

security:
  user:
    password: pass
#    ${CONFIG_SERVICE_PASSWORD}