security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: pass
#      ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://localhost:6000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: 127.0.0.1
      username: user
      password: pass
#      ${MONGODB_PASSWORD}
      database: micro
      port: 27017

server:
  context-path: /accounts
  port: 6000